### ISSUE TITLE
Can someone change University to Group

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#1]
Can someone change university etc to group as they are nearly same. Every feature is implemented but I am feeling abit hesitant to update and my windows dual core cpu is really slow. If anyone interested he can collaborate this project as well .

**Comment by vraravam** [comment]
@bloggervista - i have forked, will submit a PR in an hour or so.

**Comment by bloggervista** [comment]
@vraravam Yeah thanks bro :)

**Comment by vraravam** [comment]
@bloggervista - quick q: Has this project been released into some shared env? If so, the migrations will have to be only done incrementally. If not, we can do a direct rename - which will assume that you will be forced to recreate the db from scratch. How shall I proceed?

**Comment by bloggervista** [comment]
yea you can do direct rename.

**Comment by bloggervista** [comment]
@vraravam  Merged Thanks

**Comment by vraravam** [comment]
@bloggervista - sorry, forgot to rename the files/folders - now this should work. Please merge this commit as well into master.

**Comment by bloggervista** [comment]
@vraravam sure bro. I think we need to write test.

**Comment by vraravam** [comment]
@bloggervista - yes, im in the process of introducing rspec for some tests (based on your comment in the readme)

**Comment by bloggervista** [comment]
Where is commit bro?

**Comment by bloggervista** [comment]
Can u colloborate so you can commit with full access
