### ISSUE TITLE
Can someone implement travis for continuous integration

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#10]
Can anyone push travis related config so it will be easier for other developer to future push and check there were no problem in tests.

I am happy to merge your pr.

**Comment by henriquepjv** [comment]
Hey @bloggervista i can solve this :D

**Comment by bloggervista** [comment]
@henriquepjv  thank you :)

**Comment by henriquepjv** [comment]
@bloggervista new PR created !! 
There is some specifications there for the final travis configuration :+1:

**Comment by bloggervista** [comment]
@henriquepjv Thanks again for your great support :).
