### ISSUE TITLE
Support for postgresql and using database credentials on environment file

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#12]
As `postgres` is really a good opensource database I would like to use `postgres` on this project. 

But for user to enter database username and password I would like to use `.env` file. And please do it like this.

.env file will not be committed but `.env.example` will be committed so developer can check which which environmnet variable should be committed

`.env.example` will probably look like this
```
DB_USERNAME=
DB_PASSWORD
```

So developer can create .env and modify to look it like this.
```
DB_USERNAME: Admin
DB_PASSWORD: secret@123
```

It may seem hard but it's really easy. If any problem feel free to post.

**Comment by nenadmil** [comment]
I created pull request for this issue. https://github.com/bloggervista/Bee-Connect/pull/13

**Comment by bloggervista** [comment]
@nenadmil  Thanks bro. Can I write your name in contributor docs. I am very happy to write your name. I will close it but don't forget to reply me as i cannot write name without contributors permissions.

**Comment by nenadmil** [comment]
Yes, you can add me to your list of contributors.

**Comment by bloggervista** [comment]
done.
