### ISSUE TITLE
Integration Test for refactoring

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#15]
I guess this project will need huge refactor but as it is in public repo I don't want to break any thing on user side. So I guess we can refactor after writing test so we will know where is breaking change.

Can someone write integration test etc.. so it will help all devs using and learning this project? And we have travis-ci integrated so it will be helpful for pull request also.

Thanks.

**Comment by gregmolnar** [comment]
It looks like there is just one model spec at the moment, so better test coverage is needed for sure. Do you want to go with rspec or minitest? I favour minitest since that's shipped with rails by default.

**Comment by bloggervista** [comment]
@gregmolnar  you can do as your wish bro :)
