### ISSUE TITLE
Integrating StyleCI

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#19]
Can someone integrate styleci and its corresponding badges in readme file. you can write dummy id for badge untill i enable style ci in this repo. I will make corresponding edit.

**Comment by Yogendra0Sharma** [comment]
@bloggervista I am working on it.

**Comment by bloggervista** [comment]
@Yogendra0Sharma  Ok.

**Comment by bloggervista** [comment]
Done thanks
