### ISSUE TITLE
Updating styles.

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#2]
Only knowledge of sass is essential.

Can you please update that terrible image and fix some header stylesheet. If possible can we review some styles and best practises?

Update required only for app/stylesheet/application.scss

Thanks.

Check https://chat-ounce-shirshak.c9users.io/ for more details
admin username and password is in readme file

**Comment by Rohitgird** [comment]
I'll do this!

**Comment by henriquepjv** [comment]
Hi @bloggervista i can help you with your stylesheet organization

**Comment by bloggervista** [comment]
@henriquepjv thanks i am happy to merge

**Comment by bloggervista** [comment]
Thanks for PR
Merged #7
