### ISSUE TITLE
Chat is not real time 

### ISSUE THREAD

**Issue by yogeshmanjhi1993** [bloggervista/Bee-Connect#27]
I registered two users in the application in two separate windows(one normal and other incognito) after that  i tried messaging one user from other user but the message is not being sent or received in real time. 
Can you please specify if the chat is real time or not.

**Comment by bloggervista** [comment]
@yogeshmanjhi1993 sorry for late reply didn't got any notifications.

Have you run queue? Sidekiq queue is used to queue the message of chat.

**Comment by bloggervista** [comment]
run 
```
$ bundle exec sidekiq
```

I will close this issue after 30 days if not solved feel free to open it :)
