### ISSUE TITLE
Making responsive

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#3]
Can someone make this app responsive. I guess only little work is needed as many thing have been done.

Only need to update app/assets/stylesheets/application.sass
Thanks

Check https://chat-ounce-shirshak.c9users.io/ for more details
admin username and password is in readme file

**Comment by mdelclaro** [comment]
Hello, hope you're fine. I was taking a look at it... Isn't it responsive already?

**Comment by bloggervista** [comment]
@mdelclaro there are some problems like this:

https://pasteboard.co/GPOPv6F.png

**Comment by bloggervista** [comment]
and it would be usefull if that background image is changed and navbar background etc.. styling optimizations :)

Thanks for your query.

**Comment by mdelclaro** [comment]
Okay. I will take a look at the navbar for now :-)

**Comment by mdelclaro** [comment]
I won't be able to help you anymore. Sorry for that :(

**Comment by bloggervista** [comment]
@mdelclaro no problem.

**Comment by bloggervista** [comment]
Uf any one wants to PR then feel free to do it
