### ISSUE TITLE
SideCI failed to analyze your code.

### ISSUE THREAD

**Issue by blimey85** [bloggervista/Bee-Connect#31]
I haven't used SideCI before but when I submitted a PR just now there was an error and it didn't analyze the code. Here is the link provided in the PR to details of the problem, included here just for convenience: https://sideci.com/gh/107520275/pull_requests/30

**Comment by bloggervista** [comment]
Don't worry it just showing this error . We will fix it soon. We will accept PR anyway. Later we will write test using travis CI so it wont be any problem.

```

2018-06-10T15:12:46Z
    -> 0.03321668s
2018-06-10T15:12:46ZRunning analyzer
2018-06-10T15:12:46Z
# bundle exec querly version
2018-06-10T15:12:47Z
Querly 0.11.0
2018-06-10T15:12:47Zexit status: 0
2018-06-10T15:12:47Z
Checking if required file exists: querly.yml, querly.yaml
2018-06-10T15:12:47Z
No file found...
2018-06-10T15:12:47Z
Writing result...
2018-06-10T15:12:47Z
    -> 0.000110102s
```

If any issue feel free to reopen
