### ISSUE TITLE
Upgrading to Latest Version of rails

### ISSUE THREAD

**Issue by bloggervista** [bloggervista/Bee-Connect#9]
This project is at 5.0.1 which bugs me a lot. If anyone is interested to do I am happy to merge PR.

**Comment by ankitbhardwaj78** [comment]
i want to work on it @bloggervista

**Comment by bloggervista** [comment]
@ankitbhardwaj78  Ok Thanks I am waiting for your PR.

**Comment by bloggervista** [comment]
@ankitbhardwaj78  can you tell me how much time will it take?

**Comment by ankitbhardwaj78** [comment]
hey @bloggervista  it would be helpful if you tell me where you are getting trouble in your project bexause i am not able to find it by myself.

**Comment by bloggervista** [comment]
I just want to upgrade to latest version of rails 5.1 bro

**Comment by bloggervista** [comment]
and if you run migrate i guess there are some warning which we don't want.

**Comment by ankitbhardwaj78** [comment]
yes i will try to fix that

**Comment by bloggervista** [comment]
Actually I want 5.1 because of its javascript support. We want it to be future ready .

**Comment by bloggervista** [comment]
I guess you will not work for rails 5.1 . Thanks for upgrade to abit latest version of rails

**Comment by sebasjimenez10** [comment]
@bloggervista do you still need this done?

**Comment by bloggervista** [comment]
@sebasjimenez10  Yes I would like this project to be rails 5.1 so it would be easy for later.

**Comment by bloggervista** [comment]
@sebasjimenez10  Small changes wanted  #24

**Comment by bloggervista** [comment]
Thanks Upgraded .

**Comment by sebasjimenez10** [comment]
:) Happy to help

**Comment by bloggervista** [comment]
@sebasjimenez10  would you like to collaborate this project?

**Comment by sebasjimenez10** [comment]
Absolutely!

**Comment by bloggervista** [comment]
@sebasjimenez10  I have added you check your email.

**Comment by sebasjimenez10** [comment]
Just accepted

**Comment by bloggervista** [comment]
@sebasjimenez10 can you send me email at bloggervista@gmail.com so we can discuss any thing personal. And feel free to push any improvement you like

**Comment by sebasjimenez10** [comment]
Thanks, and yeah email me whenever you want to I'd be happy to help.
